### ISSUE TITLE
{output_prefix}_conseq_header1.txt file is missing "1" in the file name

### ISSUE THREAD

**Issue by madhushanka** [genomicsengland/COVID19_GenOMICC_AVT_analysis#2]
https://github.com/genomicsengland/COVID19_GenOMICC_AVT_analysis/blob/f9c4efe5c6cd3558f400f85ab29e0d4307af80d9/extract_consequences.sh#L11

**Comment by kousathanas** [comment]
thanks Madhu, 

fixed
