### ISSUE TITLE
ERROR: duplicate variant annotations at line 817.

### ISSUE THREAD

**Issue by madhushanka** [genomicsengland/COVID19_GenOMICC_AVT_analysis#3]
https://github.com/genomicsengland/COVID19_GenOMICC_AVT_analysis/blob/f14c195d6fc0c577f65efb359cc45880cea8edc3/create_REGENIE_maskfiles.R#L28

We got the following error  "ERROR: duplicate variant annotations at line 817." when running regenie and therefore changed the line to "annodata<-rbind(lof,missense)%>%distinct()", which seems to fix the issue.

Cheers,
Madhu

**Comment by kousathanas** [comment]
Thank you Madhu,
modified code to capture this case
best
Thanos
