### ISSUE TITLE
object LoF not found

### ISSUE THREAD

**Issue by prince26121991** [genomicsengland/COVID19_GenOMICC_AVT_analysis#4]
LOF module doesn't seem to be working for me, when I run the following command, I dont get any column name LoF
`bcftools-1.19/bcftools +split-vep vep_data/variant_sites_chr22_10K_annotated.vcf.gz -l
`0	Allele
1	Consequence
2	IMPACT
3	SYMBOL
4	Gene
5	Feature_type
6	Feature
7	BIOTYPE
8	EXON
9	INTRON
10	HGVSc
11	HGVSp
12	cDNA_position
13	CDS_position
14	Protein_position
15	Amino_acids
16	Codons
17	Existing_variation
18	DISTANCE
19	STRAND
20	FLAGS
21	VARIANT_CLASS
22	SYMBOL_SOURCE
23	HGNC_ID
24	CANONICAL
25	MANE_SELECT
26	MANE_PLUS_CLINICAL
27	TSL
28	APPRIS
29	CCDS
30	ENSP
31	SWISSPROT
32	TREMBL
33	UNIPARC
34	UNIPROT_ISOFORM
35	GENE_PHENO
36	SIFT
37	PolyPhen
38	DOMAINS
39	miRNA
40	AF
41	AFR_AF
42	AMR_AF
43	EAS_AF
44	EUR_AF
45	SAS_AF
46	AA_AF
47	EA_AF
48	gnomAD_AF
49	gnomAD_AFR_AF
50	gnomAD_AMR_AF
51	gnomAD_ASJ_AF
52	gnomAD_EAS_AF
53	gnomAD_FIN_AF
54	gnomAD_NFE_AF
55	gnomAD_OTH_AF
56	gnomAD_SAS_AF
57	MAX_AF
58	MAX_AF_POPS
59	CLIN_SIG
60	SOMATIC
61	PHENO
62	PUBMED
63	MOTIF_NAME
64	MOTIF_POS
65	HIGH_INF_POS
66	MOTIF_SCORE_CHANGE
67	TRANSCRIPTION_FACTORS

There is no LOF column, I checked warning file as well and there seems to be the actual issue,

`cat vep_data/variant_sites_chr22_10K_annotated.vcf_warnings.txt
`
WARNING: Failed to instantiate plugin LoF: Can't open /opt/micromamba/share/ensembl-vep-105.0-1/splice_data/donor_motifs/ese.txt: No such file or directory at /home1/niteshku/.vep/Plugins/loftee_splice_utils.pl line 212.

WARNING: Failed to instantiate plugin CADD: 
ERROR: Assembly is GRCh38 but CADD file does not contain GRCh38 in header.

**Comment by kousathanas** [comment]
@prince26121991 Are you running VEP with singularity? 

Can you add the following arguments to your singularity command:

`--cleanenv --no-home`

**Comment by prince26121991** [comment]
@kousathanas Thanks for the reply.
Using these arguments seems to improve the result, as there is no warning related to "CADD" now, but for LoF I am still getting the warning:

Here is my job file

` #!/bin/bash
#SBATCH --account=niteshku_907
#SBATCH --partition=main
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=16G
#SBATCH --time=1:00:00
module purge
module load gcc/11.3.0
module load python/3.9.12
prefix=variant_sites_chr22_10K
#output=variant_sites_chr22_10K_indels_cadd
repo=/scratch1/niteshku/covid_analysis/COVID19_GenOMICC_AVT_analysis
aux_data=/scratch1/niteshku/covid_analysis/vep_data


inputvcf=$1
cadd_snv_data=$2
cadd_indel_scores_tsv=$3
aux_data=$4
output_prefix=$5

#Command to feed to vep container to annotate with defaults + LoF + CADD 
cmd="vep -i /project/niteshku_907/vep/.vep/${inputvcf} \
         --assembly GRCh38 \
         --vcf \
         --format vcf \
         --cache \
         --dir_cache /project/niteshku_907/vep/.vep \
         -o /project/niteshku_907/vep/.vep/${output_prefix}.vcf \
         --plugin LoF,loftee_path:/opt/micromamba/share/ensembl-vep-105.0-1,human_ancestor_fa:/scratch1/niteshku/covid_analysis/vep_data/human_ancestor.fa.gz,conservation_file:/scratch1/niteshku/covid_analysis/vep_data/loftee.sql,gerp_bigwig:/scratch1/niteshku/covid_analysis/vep_data/gerp_conservation_scores.homo_sapiens.GRCh38.bw \
         --plugin CADD,/project/niteshku_907/vep/.vep/whole_genome_SNVs.tsv.gz,/project/niteshku_907/vep/.vep/variant_sites_chr22_10K_indels_cadd.tsv.gz \
         --everything \
         --force_overwrite \
         --offline \
         --fork 4 \
         --quiet"


#Run container
singularity exec -B ${aux_data}:/project/niteshku_907/vep/.vep:rw --cleanenv --no-home /scratch1/niteshku/covid_analysis/vep_105.2.sif $cmd

#bgzip and index output
bgzip -f /scratch1/niteshku/covid_analysis/vep_data/${output_prefix}.vcf
tabix -f /scratch1/niteshku/covid_analysis/vep_data/${output_prefix}.vcf.gz `


I am running the following command

`
 prefix=variant_sites_chr22_10K
repo=${PWD}/COVID19_GenOMICC_AVT_analysis
aux_data=${PWD}/vep_data
sbatch test2.sh  ${prefix}.vcf.gz ${aux_data}/whole_genome_SNVs.tsv.gz ${prefix}_indels_cadd.tsv.gz ${aux_data} ${prefix}_annotated`


This is my waring file

`WARNING: Failed to compile plugin LoF: Can't locate LoF.pm in @INC (you may need to install the LoF module) (@INC contains: /home1/niteshku/.vep/Plugins /opt/vep/src/ensembl-vep/modules /opt/vep/src/ensembl-vep /opt/vep/.vep/Plugins /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at (eval 40) line 2.
BEGIN failed--compilation aborted at (eval 40) line 2.`

And here is bcftools output, as you can see earlier there were 67 columns but now there are 69 columns
`0	Allele
1	Consequence
2	IMPACT
3	SYMBOL
4	Gene
5	Feature_type
6	Feature
7	BIOTYPE
8	EXON
9	INTRON
10	HGVSc
11	HGVSp
12	cDNA_position
13	CDS_position
14	Protein_position
15	Amino_acids
16	Codons
17	Existing_variation
18	DISTANCE
19	STRAND
20	FLAGS
21	VARIANT_CLASS
22	SYMBOL_SOURCE
23	HGNC_ID
24	CANONICAL
25	MANE_SELECT
26	MANE_PLUS_CLINICAL
27	TSL
28	APPRIS
29	CCDS
30	ENSP
31	SWISSPROT
32	TREMBL
33	UNIPARC
34	UNIPROT_ISOFORM
35	GENE_PHENO
36	SIFT
37	PolyPhen
38	DOMAINS
39	miRNA
40	AF
41	AFR_AF
42	AMR_AF
43	EAS_AF
44	EUR_AF
45	SAS_AF
46	AA_AF
47	EA_AF
48	gnomAD_AF
49	gnomAD_AFR_AF
50	gnomAD_AMR_AF
51	gnomAD_ASJ_AF
52	gnomAD_EAS_AF
53	gnomAD_FIN_AF
54	gnomAD_NFE_AF
55	gnomAD_OTH_AF
56	gnomAD_SAS_AF
57	MAX_AF
58	MAX_AF_POPS
59	CLIN_SIG
60	SOMATIC
61	PHENO
62	PUBMED
63	MOTIF_NAME
64	MOTIF_POS
65	HIGH_INF_POS
66	MOTIF_SCORE_CHANGE
67	TRANSCRIPTION_FACTORS
68	CADD_PHRED
69	CADD_RAW
`

**Comment by kousathanas** [comment]
@prince26121991 just to double check, are you running the vep container from here: 

quay.io/kousathanas/vep:v105

as in the repo? you must use that container as certain auxiliary files are installed in specific directories within the container.

**Comment by prince26121991** [comment]
@kousathanas  Yes you are right, I was using the wrong version of VEP, I have corrected it and now annotation file has LoF and relative columns as well, but now the warning file is giving different error, here it is:
`$ cat vep_data/variant_sites_chr22_10K_annotated.vcf_warnings.txt 
WARNING: 32556 : DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557, <$fh> line 5003.
WARNING: Plugin 'LoF' went wrong: MySQL ERROR: No such file or directory at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557, <$fh> line 5003.
DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557, <$fh> line 5003.
DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557, <$fh> line 5003.
DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557, <$fh> line 5003.
DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557, <$fh> line 5003.
DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557, <$fh> line 5003.
DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557, <$fh> line 5003.
DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557, <$fh> line 5003.
DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557, <$fh> line 5003.
DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557, <$fh> line 5003.
DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557, <$fh> line 5003.
DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557, <$fh> line 5003.
DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557, <$fh> line 5003.
DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557, <$fh> line 5003.
WARNING: 32554 : DBD::SQLite::st execute failed: file is not a database at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557, <$fh> line 5003.
WARNING: Plugin 'LoF' went wrong: MySQL ERROR: No such file or directory at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557, <$fh> line 5003.
WARNING: 32555 : DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557, <$fh> line 5003.
WARNING: Plugin 'LoF' went wrong: MySQL ERROR: No such file or directory at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557, <$fh> line 5003.
DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557, <$fh> line 5003.
WARNING: 540 : DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557.
WARNING: Plugin 'LoF' went wrong: MySQL ERROR: No such file or directory at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557.
DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557.
DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557.
DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557.
DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557.
DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557.
DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557.
DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557.
DBD::SQLite::st execute failed: database disk image is malformed at /opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 557.`



But if I am not wrong these are just warnings so we can ignore them, as I was able to create masked file now, which was my original problem, working on 4th step now.

**Comment by kousathanas** [comment]
@prince26121991 thanks, glad to know that you are getting no errors.
I will investigate this, but feel free to proceed for now to the next step.
